### ISSUE TITLE
Vivaldi works, Qutebrowser not.

### ISSUE THREAD

**Issue by JPRuehmann** [def-/time.gif#1]
I hope there is a Way to make it work in most browsers.
I´d love to use it in my Homepage if I can.
Thanks,

**Comment by def-** [comment]
Works for me in qutebrowser. But if I open it twice in a single Firefox instance, it doesn't work. Probably because the browser tries to store it and use the cached version instead of redownloading it again. I have now added a few cache controls. Please try again.

**Comment by JPRuehmann** [comment]
Ok
Qutebrowser works, Vivaldi Works, Firefox only in the first instance.
Thanks,
Which License you use?

**Comment by def-** [comment]
Added BSD3 now.

**Comment by JPRuehmann** [comment]
Ok
By the Way Chromium and Opera are working to.
