### ISSUE TITLE
cannot run in background

### ISSUE THREAD

**Issue by JPRuehmann** [def-/time.gif#2]
Hello
is there a way to make it run in the background?
If I try to run it by`timegif &> /dev/null &` it gets started in the background but is suspended until i get it to the foreground by fg.
Thanks,

**Comment by def-** [comment]
nohup timegif &

**Comment by JPRuehmann** [comment]
Won´t work.
`[2]  + suspended (tty output)  nohup timegif`
Thanks,
by the Way `stty -tostop` won´t work either.

**Comment by def-** [comment]
Well, that's how I run it right now. You could also use screen.

**Comment by JPRuehmann** [comment]
Tried screen, tmux and byobu won´t work either
they all can´t run completely unatended by for example the rc.local script in /etc.
Thanks.

**Comment by def-** [comment]
screen -d?

**Comment by JPRuehmann** [comment]
This was the Hint, thank you.
`screen -d -m timegif -X timegif` does the Trick.
