### ISSUE TITLE
https ?

### ISSUE THREAD

**Issue by JPRuehmann** [def-/time.gif#6]
Hello
Sorry it´s me again ;-)
It works like a charm as long as I am in my Local Network.
But if I try to reach it from outside I get a message of Keys that are to long.
My Server is only reachable via https I think that is the Problem.
No one should use http these days anymore.
Is there a way to make it work with https?
Thanks,

**Comment by def-** [comment]
I use an nginx proxy:

```
  location /time.gif {
    proxy_pass http://127.0.0.1:5002/;
    proxy_buffering off;
  }  
```

I will not add https support, I believe using a proper proxy https server is the better solution.

**Comment by JPRuehmann** [comment]
I won´t get it to work because the behaviour is the same only the address get changed.
I am using apache and tried reverse proxying no chance.

**Comment by def-** [comment]
I don't know Apache well, but generally you would create a regular https server there, with certificates and everything. Once that works you add a proxy for a specific location and make sure that there is no buffering from Apache on the proxy connection.

**Comment by JPRuehmann** [comment]
Ive tried that, Ok I will try further I tell you if it works how I did it.
Thank you for helping.
