### ISSUE TITLE
Page load never stop

### ISSUE THREAD

**Issue by ghost** [def-/time.gif#7]
If visit `https://hookrace.net/blog/time.gif/` page load never stop. It's very cute(endless clock), but it's very bad for web projects.

**Comment by def-** [comment]
That seems like accurate browser behaviour for me. You're not supposed to use endless gifs in real web projects. Maybe some javascript could be used to hide it.

**Comment by ghost** [comment]
Maybe you can add select where ppls can choose timezone?
