### ISSUE TITLE
Can´t compile anymore

### ISSUE THREAD

**Issue by JPRuehmann** [def-/time.gif#8]
Hello
since the last git pull I can´t compile time-gif anymore.
I onlyget 
`Codec/Picture/Gif/LZWEncoding.hs:4:0:
     error: missing binary operator before token "("
     #if !MIN_VERSION_base(4,8,0)
     ^

Codec/Picture/Gif/LZWEncoding.hs:14:0:
     error: missing binary operator before token "("
     #if MIN_VERSION_containers(0,5,0)
     ^
`
What I do wrong?
`ghc -O2 --make time-gif.hs -threaded -rtsopts`

**Comment by def-** [comment]
old ghc version? I think only GHC 8 supports that. Alternatively you can try `cabal build`, that should set the proper includes.

**Comment by JPRuehmann** [comment]
Thanks,
cabal works after blindly installing all 900 libghc packages.

**Comment by def-** [comment]
You could also have run `cabal install --only-dependencies`

**Comment by JPRuehmann** [comment]
The Problem is on Kubuntus side that the Package Names not consistently use the same names as the includes in the source so I can´t see from the output of cabal which Packages I must Install with apt.
Not your error.
Thanks,
